version: '1'
services:
  server:
    build: .
    image: my-golang-app
    container_name: golang-server
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - docker-practice

networks:
  docker-practice:
    name: docker-practice
